@startuml
== 流程到达外部系统审批节点 ==
客户端 -> 客户端 : 定时任务，查询需要外部系统审批的任务
note left
    固定查询【指派用户=机器人】的待办任务
    其他查询条件跟普通用户查询待办任务类似
end note
客户端 -> 流程引擎 : 查询待办任务
流程引擎 -> 流程引擎 : 待办任务查询
客户端 <-- 流程引擎 : 返回查询结果
loop 机器人待办任务
    客户端 -> 外部系统 : 发起审批请求
    客户端 <-- 外部系统 : 审批结果
    note left
        同步/异步
    end note
    客户端 -> 流程引擎 : 任务审批请求
    note left
        任务审批流程
    end note
end loop

@enduml