@startuml
客户端 -> 客户端 : 业务数据保存，初始状态
note left
    业务相关数据更新
end note
客户端 -> 客户端 : 保存请求流水记录
note left #00FFFF
    要记录请求流水，做超时补偿
end note
客户端 -> 流程引擎 : 请求进行一些流程操作
流程引擎 -> 流程引擎 : 流程操作的处理
note right
    流程相关数据更新
end note
客户端 <-- 流程引擎 : 响应结果
alt 客户端正常接收
    客户端 -> 客户端 : 处理响应结果
    note left
        正常情况
    end note
    客户端 -> 客户端 : 更新流水状态
    note left #00FFFF
        更新流水状态为成功/失败...
    end note
else 客户端接收响应超时
    客户端 -> 客户端 : 重试补偿操作（批量操作）
    note left
        此时流程数据可能更新成功/失败，
        需要客户端进行补偿处理
    end note
    客户端 -> 流程引擎 : 查询流水号的处理状态
    客户端 <-- 流程引擎 : 响应结果
    alt 响应成功
        客户端 -> 客户端 : 更新流水状态
    else 响应超时或失败
        客户端 -> 客户端 : 等待后续继续重试查询
    end alt
    note left #00FFFF
        增加业务系统的交互复杂度
    end note
end alt

== 后续业务处理 ==
客户端 -> 客户端 : 查询上一次的请求流水状态
alt 终态
    客户端 -> 客户端 : 正常业务处理
else 非终态
    客户端 -> 客户端 : 等待补偿查询，或者主动进行一次查询
    note left #00FFFF
        影响后续业务处理效率
    end note
end alt

@enduml