@startuml
客户端 -> 客户端 : 业务数据保存，初始状态
note left
    业务相关数据更新
end note
客户端 -> 流程引擎 : 请求进行一些流程操作
流程引擎 -> 流程引擎 : 流程操作的处理
note right
    流程相关数据更新
end note
客户端 <-- 流程引擎 : 响应结果
alt 客户端正常接收
    客户端 -> 客户端 : 处理响应结果
    note left
        正常情况
        流程到达下个任务节点
    end note
else 客户端接收响应超时
    客户端 -> 客户端 : 记录异常流水信息
    客户端 -> 客户端 : 重试补偿操作（批量操作）
    note left
        此时流程数据可能更新成功/失败，
        需要客户端进行补偿处理
    end note
    客户端 -> 流程引擎 : 查询流水号的处理状态
    客户端 <-- 流程引擎 : 响应结果
    alt 响应成功
        客户端 -> 客户端 : 更新流水状态
    else 响应超时或失败
        客户端 -> 客户端 : 等待后续继续重试查询
    end alt
end alt

@enduml