@startuml
客户端 -> 客户端 : 业务数据持久化
note left
    页面人工审批
    业务相关数据更新
end note
客户端 -> 流程引擎 : 请求进行一些流程操作
流程引擎 -> 流程引擎 : 流程操作的处理
note right
    流程相关数据更新
end note
客户端 <-- 流程引擎 : 响应结果
alt 客户端正常接收
    客户端 -> 客户端 : 处理响应结果
    note left
        正常情况
        流程到达下个任务节点；
        或流程处理内部异常，
        回滚更新数据再次提交
    end note
else 客户端接收响应超时
    alt 流程数据实际更新成功
        客户端 -> 客户端 : 下一个任务审批人可以看到待办任务
    else 流程数据实际更新失败
        客户端 -> 客户端 : 任务节点停在当前审批流程，可再次提交
        note left
            再次提交后业务数据不会更新
            只会再次请求流程引擎更新流程
        end note
    end alt
end alt

@enduml